#!/usr/bin/env perl
#
# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
# Copyright 2014 Andreas Guldstrand <andreas.guldstrand@gmail.com>
#
# Licensed under the terms of the GNU GPL v3, or any later version.

use strict;
use warnings;
use utf8;
use Getopt::Long;

# default values
my $cpu_warn = $ENV{T_WARN} // 65;
my $cpu_crit = $ENV{T_CRIT} // 85;
my $cpu_temp = -1;
my $decimals = $ENV{DECIMALS} // 2;
my $label = $ENV{LABEL} // "";
my $color_normal = $ENV{COLOR_NORMAL} // "#FFFFFF";
my $color_warn = $ENV{COLOR_WARN} // "#FFFC00";
my $color_crit = $ENV{COLOR_CRIT} // "#FF0000";

sub help {
    print "Usage: cpu_temp [-w <warning>] [-c <critical>] [-d <decimals>]\n";
    print "-w <percent>: warning threshold to become yellow\n";
    print "-c <percent>: critical threshold to become red\n";
    print "-d <decimals>:  Use <decimals> decimals for percentage (default is $decimals) \n"; 
    exit 0;
}

GetOptions("help|h" => \&help,
           "w=i"    => \$t_warn,
           "c=i"    => \$t_crit,
           "d=i"    => \$decimals,
);

# Get CPU usage
$ENV{LC_ALL}="en_US"; # if mpstat is not run under en_US locale, things may break, so make sure it is
open (SENSORS, 'sensors |') or die;
while (<SENSORS>) {
    $cpu_temp = $1;
    last;
}
close(SENSORS);

$cpu_temp eq -1 and die 'Can\'t find CPU information';

# Print short_text, full_text
print "${label}";
printf "%.${decimals}f%%\n", $cpu_temp;
print "${label}";
printf "%.${decimals}f%%\n", $cpu_temp;

# Print color, if needed
if ($cpu_usage >= $t_crit) {
    print "${color_crit}\n";
} elsif ($cpu_usage >= $t_warn) {
    print "${color_warn}\n";
} else {
    print "${color_normal}\n";
}

exit 0;
